movielens_data: '20m' #[20m or 100k]
learning_rate: 0.001
epochs: 2
batch_size: 256
optimizer: 'sgd' #[adam or sgd]
model: 'mlp' #[mlp | gmf | nmf | joint_nmf]
latent_dims: 16

weight_file: 'models/mlp_16_20m'
