movielens_data: '100k' #[20m or 100k]
learning_rate: 0.07
weight_decay: 0.0001 # Only used for Adam
epochs: 5
batch_size: 128
optimizer: 'adam' #[adam or SGD]
model: 'nmf' #[mlp | gmf | nmf | joint_nmf]
latent_dims: 64
alpha: 0.5

gmf_weights_file: 'models/gmf_64_100k'
mlp_weights_file: 'models/mlp_64_100k'

weight_file: 'models/nmf_64_100k'
